### ISSUE TITLE
Error starting storm-docker

### ISSUE THREAD

**Issue by mavencode01** [viki-org/storm-docker#9]
I got this error when running `./start-storm.sh all`

RuntimeError: IP address of this machine does not match any IP address supplied in the `storm.yaml` -> `storm.zookeeper.servers` section of `config/storm-supervisor.yaml`.

```
  Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/developer/development/docker/storm-docker/docker_python_helpers/run_zookeeper.py", line 66, in <module>
    """).strip()
RuntimeError: IP address of this machine does not match any IP address supplied in the `storm.yaml` -> `storm.zookeeper.servers` section of `config/storm-supervisor.yaml`.
```

**Comment by yanhan** [comment]
Hi @pkadetiloye , mind showing your `config/storm-supervisor.yaml` file?
